name: pasakay
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.0
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  flutter_polyline_points: ^2.0.0
  get: 4.6.6
  google_maps_flutter: ^2.6.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  flutter:
    sdk: flutter
  toastification: ^2.0.0
  geoflutterfire2: ^2.3.15
  animated_splash_screen: ^1.3.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  firebase_messaging: ^14.9.4
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #- .env
