// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0s0YkPaTkVCTplRpIB2xgZaPEpy9vTps',
    appId: '1:604932579251:web:06a35dbb45ba511b03f5c6',
    messagingSenderId: '604932579251',
    projectId: 'pasakay-67ea7',
    authDomain: 'pasakay-67ea7.firebaseapp.com',
    storageBucket: 'pasakay-67ea7.appspot.com',
    measurementId: 'G-MLJTENG4XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCIkXEPFYb6HPd07Z_sOEI7ngrYtejvqo',
    appId: '1:604932579251:android:25c1a8c9f5f6ed3b03f5c6',
    messagingSenderId: '604932579251',
    projectId: 'pasakay-67ea7',
    storageBucket: 'pasakay-67ea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5StaZkYUa-pI5g787JoT5mA7Lb6pN0E',
    appId: '1:604932579251:ios:df348582795bcf0103f5c6',
    messagingSenderId: '604932579251',
    projectId: 'pasakay-67ea7',
    storageBucket: 'pasakay-67ea7.appspot.com',
    iosBundleId: 'com.pasakay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5StaZkYUa-pI5g787JoT5mA7Lb6pN0E',
    appId: '1:604932579251:ios:31521e3de150004b03f5c6',
    messagingSenderId: '604932579251',
    projectId: 'pasakay-67ea7',
    storageBucket: 'pasakay-67ea7.appspot.com',
    iosBundleId: 'com.pasakay.RunnerTests',
  );
}
